### ISSUE TITLE
probably a silly question, but how does one run it?

### ISSUE THREAD

**Issue by hiphamster** [veonim/veonim#614]
There's not makefile, and the binary under runtime/darwin does nothing

**Comment by khalidchawtany** [comment]
Clone to a directory then cd into it and run one of these:
`npm install && npm run build && npm run start:release`

OR 

`npm install && npm run build && npm run package`
Then run the produced binary which should be in `dist` dir.

**Comment by breja** [comment]
What are you trying to run? Are you trying to run the downloaded binaries or build from source?

**Comment by tanyaionova** [comment]
A similar question: how does one build one of release packages?
Specifically, I am interested in appimage, but it will be great, if anybody will help with dmg and exe bundles too.

**Comment by breja** [comment]
To build a release binary, after you've run the build steps, then `npm run package`. I don't think cross-platform builds work (so to build .dmg -> Mac, .exe -> Windows, .appimage -> Linux, etc.)

More details here: https://github.com/veonim/veonim#development

**Comment by hiphamster** [comment]
I didn't realize this required node. I think @breja Answered the question on how to build. I haven't tried it yet.

**Comment by hiphamster** [comment]
I followed the steps, got the mac binary. When i run it, i see a blank window, it doesn't react to any vi/vim commands, just sits there.

**Comment by theHamsta** [comment]
Is neovim installed in your $PATH?

**Comment by hiphamster** [comment]
@theHamsta Yup, neovim is in the path, i use it regularly in the terminal.

**Comment by hiphamster** [comment]
Perhaps something else is missing? Are there any dependencies I might not be aware of? A simple build guide would be very helpful.

**Comment by breja** [comment]
`npm install` should bring in all dependencies. Are you seeing any errors in the devtools console?

**Comment by oldsouless** [comment]
Built the dmg per the directions and installed into Applications. I'm seeing the blank screen @hiphamster described. Here's the dev tools error: 
`/Applications/veonim.app/Contents/Resources/app/build/render/webgl-utils.js:20 Uncaught TypeError: Cannot read property 'getExtension' of null
    at Object.create [as default] (/Applications/veonim.app/Contents/Resources/app/build/render/webgl-utils.js:20)
    at Object.nutella [as default] (/Applications/veonim.app/Contents/Resources/app/build/render/webgl.js:9)
    at Object.<anonymous> (/Applications/veonim.app/Contents/Resources/app/build/windows/window-manager.js:14)
    at Object.<anonymous> (/Applications/veonim.app/Contents/Resources/app/build/windows/window-manager.js:192)
    at Module._compile (internal/modules/cjs/loader.js:693)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)`

As well as one of the following two errors after every quit:
`Uncaught Exception:
Error: Object has been destroyed
    at App.electron_1.app.on (/Applications/veonim.app/Contents/Resources/app/build/bootstrap/main.js:84:33)
    at App.emit (events.js:182:13) `

`Uncaught Exception:
Error: ENOENT: no such file or directory, open '/undefined/veonim/settings.json'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Object.writeFileSync (fs.js:1168:35)
    at Object.set (/Applications/veonim.app/Contents/Resources/app/build/support/settings-handler.js:27:14)
    at App.electron_1.app.on (/Applications/veonim.app/Contents/Resources/app/build/bootstrap/main.js:86:34)
    at App.emit (events.js:182:13)`

**Comment by breja** [comment]
Thanks for the stack trace, it's very helpful. The missing `getExtension` is because the app was not able to get a WebGL context. I'm not really sure why this would be - perhaps virtual machines that are software only rendering?

Are you seeing a blank screen as well on the prebuilt binaries? Or you are not able to run the prebuilt binaries? What kind of OS and GPU are you trying to run veonim in?

The other two errors can be fixed without much ado - I don't think they should affect much in the grand scheme of things.

**Comment by breja** [comment]
Closing this out because there are a number of older issues together here.

To the last question: WebGL does have higher GPU requirements. I don't know the specifics but I use https://webglreport.com/?v=2 to verify support.
