### ISSUE TITLE
Error with flow for vscode extension

### ISSUE THREAD

**Issue by wmonk** [veonim/veonim#623]
When launching veonim i'm getting this error in the devtools.

```
flowtype.flow-for-vscode EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src blob: data 'self' 'unsafe-inline'".
    at /Users/will/.config/veonim/extensions/flowtype.flow-for-vscode/extension/node_modules/prettier/index.js:40203:21
    at createCommonjsModule (/Users/will/.config/veonim/extensions/flowtype.flow-for-vscode/extension/node_modules/prettier/index.js:193:35)
    at Object.<anonymous> (/Users/will/.config/veonim/extensions/flowtype.flow-for-vscode/extension/node_modules/prettier/index.js:40010:18)
    at Object.<anonymous> (/Users/will/.config/veonim/extensions/flowtype.flow-for-vscode/extension/node_modules/prettier/index.js:42016:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.Module._load.args [as _load] (/Users/will/Code/veonim/dist/mac/veonim.app/Contents/Resources/app/build/support/fake-module.js:9:7)

```

**Comment by breja** [comment]
I'll check it out. Probably need to tweak the CSP to allow extensions more permissions.

Note to self: what does VSCode allow in their CSP?

**Comment by breja** [comment]
The built-in extension host was never 100% compatible with all vscode extensions. By this point the built-in extension host has fallen very far behind in compatibility with the vscode API. The current approach is flawed and as such vscode extension support will be deprecated/removed.

There is new experimental work being done on [Tirion](https://github.com/veonim/tirion) which will instead attempt to create a bridge between Neovim and the Code Extension host without emulation. If that experiment is successful it will be integrated in Veonim.
